services:
    cloudbeaver:
        image: 'dbeaver/cloudbeaver:${CLOUDBEAVER_IMAGE_VERSION}'
        container_name: 'cloudbeaver'
        restart: always
        ports:
            - '8978:8978' # Web interface port
        volumes:
            - cloudbeaver_data:/opt/cloudbeaver/workspace
        network_mode: 'host'

volumes:
    cloudbeaver_data: