services:
    postgres:
        image: 'postgres:${POSTGRES_IMAGE_VERSION}'
        environment:
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: /data/postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
